places_remember/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.urls import include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
     path('remember/', include('remember.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/remember/index/', permanent=True)),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

remember/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    path('', views.login, name='login'),
    url('remembers/$', views.RememberListView.as_view(), name='remembers'),
    url('index/$', views.index, name='index'),
    url(r'^add/$', views.add_remember, name='add_remember'),
    url(r'remembers/(?P<pk>[a-z0-9-]+)$', views.RememberDetailView.as_view(), name='remember_detail')
]

remember/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.


class Remember(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Уникальный номер воспоминания")

    title = models.CharField(max_length=200, help_text='Название воспоминания')
    description = models.TextField(max_length=2000, help_text='Описание воспоминания')
    id_user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    map_coordinates = models.CharField(max_length=100, help_text="Координаты карты", default='0.0;0.0')

    def __str__(self):
        return f'{self.id}, {self.title}'

    def get_absolute_url(self):
        return reverse('remember_detail', args=[str(self.id)])

remember/forms.py
from django import forms
from .models import Remember


class RememberForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Remember
        fields = ('title', 'description', 'map_coordinates')

remember/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import RememberForm
from .models import Remember
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

@login_required
def index(request):
    return render(
        request,
        'index.html'
    )


def login(request):
    return render(request, 'login.html')


@login_required
def add_remember(request):
    if request.method == 'POST':
        form = RememberForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.id_user = request.user

            post.save()
        return HttpResponseRedirect(reverse('remembers'))
    else:
        form = RememberForm()

    return render(
        request,
        'add_remember.html',
        context={'form': form}
    )


class RememberListView(LoginRequiredMixin, generic.ListView):
    model = Remember

    def get_queryset(self):
        queryset_all = super(RememberListView, self).get_queryset()
        queryset_user = queryset_all.filter(id_user=self.request.user)
        return queryset_user


class RememberDetailView(LoginRequiredMixin, generic.DetailView):
    model = Remember

    def get_queryset(self):
        queryset_all = super(RememberDetailView, self).get_queryset()
        return queryset_all

    def get_context_data(self, **kwargs):
        temp = super(RememberDetailView, self).get_context_data(**kwargs)
        remember = temp.get('remember')
        if remember:
            if remember.id_user != self.request.user:
                temp = None
        return temp

remember/templates/add_remember.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Добавить воспоминание</h1>
    <script type="text/javascript">
        ymaps.ready(init);
        function init() {
            let myMap = new ymaps.Map("map_add", {
                center: [56.826774, 60.616597],
                zoom: 12
            });
            myPlacemark = new ymaps.Placemark([55.661574, 37.573856]);
            myMap.geoObjects.add(myPlacemark)
            {#myMap.geoObjects.remove(myPlacemark)#}
            myMap.events.add('click', function (e) {
                let coords = e.get('coords');
                let title_remember = document.getElementById('id_map_coordinates');
                title_remember.value = `${coords[0].toPrecision(8)}; ${coords[1].toPrecision(8)}`;
                myPlacemark.geometry.setCoordinates(coords)

            });

        }
    </script>
    <div>
    <form style="" method="POST" class="remember_form">{% csrf_token %}
        <div class="row">
            <div class="col-md-5 ">
                <div class="form-group">
                    <label for="id_title">Название</label>
                    <div>{{ form.title }}</div>
                    {{ form.title.error }}
                </div>
                <div class="form-group">
                    <label for="id_description">Описание</label>
                    <div>{{ form.description }}</div>
                </div>
            </div>
            <div style="" class="col-md-6">
                <div style="" class="form-group">
                    <label for="id_description">Место</label>
                    <div id="map_add" style="width: 100%; height: 400px;"></div>
                    <br>Координаты места: <input class="form-control" style="text-align:center; width: 200px" readonly value="" name="map_coordinates" id="id_map_coordinates">
                </div>
            </div>

        </div>
        <div style="" class="row">
            <div style="text-align:left; width: 100%" class=" col-md-3">
                <button style="width: 250px" type="submit" class="btn btn-primary">Сохранить воспоминание</button>
            </div>
        </div>

    </form>
    </div>


{% endblock %}

remember/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>Places Remember</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://api-maps.yandex.ru/2.1/?apikey=a46dee32-68ec-46a3-af1f-06e9cc4498c8&lang=ru_RU"
            type="text/javascript">

    </script>
    <style>
        .background_img {
            background: url('/static/background.jpg') no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
            position: relative;
            height: 100%;

        }

        .jumbotron {
            background-color: rgba(230, 230, 230, 0.85);
        }
    </style>
    {% load static %}
</head>

<body class="background_img">
<div class="container-fluid" style="padding: 10px; ">

    <div class="row">
        {% if user.is_authenticated %}
            <div class="col-sm-2">
                {% block sidebar %}
                    <div class="sidebar-nav list-group ">
                        {#                    <a class="list-group-item list-group-item-action" href="{% url 'index' %}">Главная</a>#}

                        <a class="list-group-item list-group-item-action" href="{% url 'remembers' %}">Мои
                            воспоминания</a>
                        <a class="list-group-item list-group-item-action" href="{% url 'add_remember' %}">Добавить
                            воспоминание</a>
                        <a class="list-group-item list-group-item-action" href="{% url 'logout' %}">Выйти</a>

                    </div>
                {% endblock %}
            </div>

            <div class="col-md-10 ">

        {% else %}
            <div>
        {% endif %}
        <div class="jumbotron">
            {% block content %}{% endblock %}
        </div>
        </div>
        </div>

    </div>
</body>
</html>

remember/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>PlacesRemember</h1>

    <h3>Добро пожаловать,
        {% if user.first_name and user.last_name %}
            <b>{{ user.first_name }} {{ user.last_name }}</b></h3>
        {% else %}
            к сожалению, не знаю вашего имени
        {% endif %}

{% endblock %}

remember/templates/login.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="card ">

        <div class="card-header text-center">
            <h1>PlacesRemember</h1>
        </div>
        <div style="padding-top: 20px; "  class=" lead">
            <div class="row row-centered row-conformity" >
                <div  class="col-sm-6 col-md-5 col-md-push-1 text-justify" >
                    <b>PlacesRemember</b> - это не просто воспоминания.
                <br>Здесь Вы можете поставить точку на карте, ввести название и
                описание места.
                    <br>Мы сохраним Ваши заметки.
                    </div>
                <div  class="col-sm-6 col-md-5 col-md-push-1 text-justify" >

                    В любой момент Вы можете освежить в памяти не только самые яркие впечатления, но и <u>геолокацию</u> с
                точными
                координатами вашего путешествия.
                </div>
            </div>

        </div>

        <hr style="background-color: #666666; height: 2px">
        <div class="lead text-center">
            Чтобы воспользоваться сайтом, необходимо авторизоваться
        </div>
        <div class=" text-center">
            <button type="button" value="" style="min-width: 250px; min-height: 50px" class="btn btn-primary"
                    onClick='location.href="{% url 'social:begin' 'facebook' %}"'>Login with Facebook
            </button>
        </div>

    </div>



{% endblock %}

remember/templates/logout.html
{% extends "base_generic.html" %}

{% block content %}
<h1>До свидания!</h1>



{% endblock %}

remember/templates/remember/remember_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <script type="text/javascript">
        ymaps.ready(init);
        function init() {
            let coords_text = "{{remember.map_coordinates}}".replace(/&quot;/g, "\"")
            let coords = [parseFloat(coords_text.split(';')[0]), parseFloat(coords_text.split(';')[1])];
            let myMap = new ymaps.Map("map_detail", {
                center: coords,
                zoom: 12
            });
            myPlacemark = new ymaps.Placemark(coords);
            myMap.geoObjects.add(myPlacemark)
        }
    </script>

    <h2>Воспоминание: <b>{{ remember.title }}</b></h2>
            <hr style="background-color: #666666; height: 2px">
    <div class="row">
        <div class="col-md-5">
            <div class="form-group">
                <label for="id_title">Описание</label>
                <div><p>{{ remember.description }}</p></div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="id_title">Место</label>
                <div id="map_detail" style="width: 600px; height: 400px"></div>
            </div>
        </div>
    </div>

{% endblock %}

remember/templates/remember/remember_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Мои воспоминания</h1>
    <div style="width: 75%; max-width: 800px; min-width: 400px; margin: 0 auto; padding-top: 15px">
    {% if remember_list %}
            <div class="list-group " >
                {% for remember in remember_list %}
                    <div class=" ">
                        <a class=" list-group-item-action list-group-item"
                           href="{{ remember.get_absolute_url }}">{{ remember.title }}</a>
                    </div>
                {% endfor %}
            </div>
    {% else %}
        К сожалению, вы не записали еще ни одного воспоминания
    {% endif %}
</div>


{% endblock %}